#!/usr/bin/env bash

DIR="$HOME/.config/sway"
CONFIG="$DIR/alacritty/config.toml"


if [[ "$XDG_SESSION_TYPE" == "wayland" && "$XDG_CURRENT_DESKTOP" == "sway" ]]; then
  alacritty --class="float,size-sm" --config-file "$CONFIG" ${@}
fi

