#!/usr/bin/env bash

mount_disk() {
    local label="$1"
 
    if udisksctl mount -b "/dev/disk/by-label/$label"; then
        notify-send -u low -h string:x-dunst-stack-tag:automount "Mounted $label"
    else
        notify-send -u crit -h string:x-dunst-stack-tag:automount "Failed to mount <$label>"
    fi
}

# # mount disks
# if mount | grep -q "takimoysha/segment-1"; then
#     notify-send -u low -h string:x-dunst-stack-tag:automount "Already mounted Segment-1"
# else
#     sleep 1    
#     # code ...
# fi

sleep 1;

mount_disk "segment-1"
mount_disk "devlab"
mount_disk "p-media"

return 0
