#!/usr/bin/env bash

mount_disk() {
    local label="$1"
 
    if udisksctl mount -b "/dev/disk/by-label/$label"; then
        notify-send -u low -h string:x-dunst-stack-tag:automount "Mounted $label"
    else
        notify-send -u crit -h string:x-dunst-stack-tag:automount "Failed to mount <$label>"
    fi
}

sleep 1;

mount_disk "devlab"
mount_disk "p-media"

return 0
