[icons]
icons = "awesome4"

[icons.overrides]
backlight = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 1

[[block]]
block = "temperature"
good = 50
idle = 60
info = 70
warning = 95

[[block]]
block = "memory"
warning_mem = 70
critical_mem = 90
format = " RAM: $mem_used_percents.eng(w:2) "
format_alt = " SWAP: $swap_used_percents.eng(w:2) "

# [[block]]
# block = "net"
# format = " $icon { $ssid | wired $device } "
# interval = 5

# [[block]]
# block = "networkmanager"
# on_click = "alacritty -e nmtui"
# interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
# interface_name_include = []

# [[block]]
# block = "backlight"
# invert_icons = false

# [[block]]
# block = "notify"
# driver = "dunst"

[[block.click]]
button = "right"
action = "show"

# [[block]]
# block = "pacman"
# interval = 3600
# format = "$icon $pacman + $aur = $both updates available "
# format_singular = "$icon $both update available "
# format_up_to_date = ""
# critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command = "paru -Qua"

# [[block]]
# block = "toggle" 
# format = " $icon picom "
# command_state = "ps ax | grep picom | grep -v grep"
# command_on = "picom -b --config /home/takimoysha/.config/sway/picom.conf"
# command_off = "killall -e picom"
# state_on = "good"
# state_off = "warning"

[[block]]
block = "time"
interval = 1
# [block.format]
# full = " $icon $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S(%a)') "


[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "docker"
[[block]]
block = "battery"
interval = 10
format = " $percentage $icon "
not_charging_format = " $icon  "

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (US)" = "US"
"Russian (N/A)" = "RU"
